services:
  abelohost_shop:
    container_name: abelohost-node
    build:
      context: .
      dockerfile: .docker/npm/Dockerfile
      target: prod
      # change target for development -> dev
    volumes:
      - ./src:/usr/src/app
    ports:
      - "80:3000"